### ISSUE TITLE
Cannot run migration tool on Windows 11

### ISSUE THREAD

**Issue by webvictim** [P-St/Migrate2WinSSHTerm#13]
I downloaded and extracted [Migrate2WinSSHTerm-0.19.zip](https://github.com/P-St/Migrate2WinSSHTerm/releases/download/0.19/Migrate2WinSSHTerm-0.19.zip) from the releases page.

When trying to run the migration tool in a terminal, I get a Python error:

```
C:\Users\gus\Desktop\Migrate2WinSSHTerm>Migrate2WinSSHTerm.exe
Traceback (most recent call last):
  File "Migrate2WinSSHTerm.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "wx\__init__.py", line 17, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "wx\core.py", line 12, in <module>
ImportError: DLL load failed while importing _core: The specified module could not be found.
[5620] Failed to execute script 'Migrate2WinSSHTerm' due to unhandled exception!
```

OS build info:
![image](https://github.com/user-attachments/assets/57200868-3058-48fa-bd3a-09eb3d4a198c)

This is a Windows VM running arm64 - maybe it's an arch issue?

```
C:\Users\gus\Desktop\Migrate2WinSSHTerm>wmic os get osarchitecture
OSArchitecture
ARM 64-bit Processor
```

**Comment by P-St** [comment]
Thanks for your feedback. I tried to reproduce it on my build system (Windows 11, arm64, 22631.3880) and on a x64 system with the same Windows version, however it is working as expected on both systems.

Do you get the same error if you try to launch an older version, e.g. [0.18](https://github.com/P-St/Migrate2WinSSHTerm/releases/download/0.18/Migrate2WinSSHTerm-0.18.zip)?

**Comment by P-St** [comment]
I could now reproduce the bug, after uninstalling Python on my build system. I will try to fix it

**Comment by webvictim** [comment]
Thanks. I can confirm I don't have Python installed on my system either.

**Comment by P-St** [comment]
I made a new build 0.19b, which I can run even if Python is not installed on my arm64 system. Does it work for you too?
[Migrate2WinSSHTerm-0.19b.zip](https://github.com/user-attachments/files/16515848/Migrate2WinSSHTerm-0.19b.zip)

**Comment by webvictim** [comment]
I tried this one too - unfortunately, I get the same error:

```
C:\Users\gus\Desktop\Migrate2WinSSHTerm-0.19b>Migrate2WinSSHTerm.exe
Traceback (most recent call last):
  File "Migrate2WinSSHTerm.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "wx\__init__.py", line 17, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "wx\core.py", line 12, in <module>
ImportError: DLL load failed while importing _core: The specified module could not be found.
[11004] Failed to execute script 'Migrate2WinSSHTerm' due to unhandled exception!
```

**Comment by P-St** [comment]
Thanks for testing. As I don't know the reason why it doesn't work I switched from PyInstaller to Nuitka to create the exe file. The result is 0.19c. Does it work for you?
[Migrate2WinSSHTerm-0.19c.zip](https://github.com/user-attachments/files/16530652/Migrate2WinSSHTerm-0.19c.zip)

**Comment by webvictim** [comment]
Different error now!

```
C:\Users\gus\Desktop\Migrate2WinSSHTerm-0.19c>Migrate2WinSSHTerm.exe
Traceback (most recent call last):
  File "C:\Users\gus\Desktop\MIGRAT~1.19C\Migrate2WinSSHTerm.py", line 4, in <module>
  File "C:\Users\gus\Desktop\MIGRAT~1.19C\wx\__init__.py", line 17, in <module wx>
  File "C:\Users\gus\Desktop\MIGRAT~1.19C\wx\core.py", line 12, in <module wx.core>
ImportError: LoadLibraryExW 'C:\Users\gus\Desktop\MIGRAT~1.19C\wx\_core.pyd' failed: The specified module could not be found.
```

**Comment by P-St** [comment]
Thanks, I added a missing dll and created a new version 0.19d:
[Migrate2WinSSHTerm-0.19d.zip](https://github.com/user-attachments/files/16533982/Migrate2WinSSHTerm-0.19d.zip)

If this still doesn't work, could you install the latest VC++ Redistributable package (x64)? You can find it [here](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170#latest-microsoft-visual-c-redistributable-version).

EDIT: I just tried the version 0.19d on a system with no VC++ Redistribitables installed - it still doesn't work. It seems the VC++ Redistributable package has to be installed as a requirement.

**Comment by webvictim** [comment]
As you noticed, it didn't work before installing the VC++ Redistributable package:

```
C:\Users\gus\Desktop\Migrate2WinSSHTerm-0.19d>Migrate2WinSSHTerm.exe
Traceback (most recent call last):
  File "Migrate2WinSSHTerm.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "wx\__init__.py", line 17, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "wx\core.py", line 12, in <module>
ImportError: DLL load failed while importing _core: The specified module could not be found.
[2868] Failed to execute script 'Migrate2WinSSHTerm' due to unhandled exception!
[10204] WARNING: failed to remove temporary directory: C:\Users\gus\AppData\Local\Temp\_MEI102042
```

It did work afterwards, however!

I can also confirm that all the previous versions also now work too. There was a segfault from 0.19c after exit, however:

```
C:\Users\gus\Desktop\Migrate2WinSSHTerm-0.19c>Migrate2WinSSHTerm.exe
Nuitka: A segmentation fault has occurred. This is highly unusual and can
have multiple reasons. Please check https://nuitka.net/info/segfault.html
for solutions.
```

I see you've added a note to the README advising to install the VC++ package so I think we can close this. Thanks for the assistance!

**Comment by P-St** [comment]
Thanks again for testing! I will continue to use PyInstaller for generating the executable
